// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: MIT-0

import React from 'react';
import { Callout, Table } from '../components/DocComponents';
import { Settings, Database, Activity } from 'lucide-react';

export const EnvironmentVariables: React.FC = () => {
  return (
    <div className="bg-white rounded-xl border border-slate-200 shadow-sm">
      <div className="p-8 border-b border-slate-200">
        <h1 className="text-3xl font-bold text-slate-900 mb-3 flex items-center gap-3">
          <Settings className="w-8 h-8 text-indigo-600" />
          Environment Variables
        </h1>
        <p className="text-lg text-slate-600">
          Lambda environment variables set automatically by the CDK deployment
        </p>
      </div>

      <div className="p-8 space-y-8">
        <Callout type="info" title="No manual configuration">
          There is nothing to configure by hand: CDK wires every value below into the Lambda
          functions at deploy time (table names, API ID, log groups), and the frontend
          discovers its API and Cognito settings at runtime. This reference exists so you can
          understand and troubleshoot the deployed functions.
        </Callout>

        <section>
          <h2 className="text-2xl font-bold text-slate-900 mb-4">Lambda Functions</h2>
          <Table
            headers={['Variable', 'Description', 'Set on']}
            rows={[
              [
                <code className="text-sm">CHANNELS_TABLE_NAME</code>,
                'DynamoDB data table name (generated by CDK)',
                'signal processor, channel manager, external actions',
              ],
              [
                <code className="text-sm">PREFERENCES_TABLE_NAME</code>,
                'DynamoDB preferences table name',
                'preferences',
              ],
              [
                <code className="text-sm">API_ID</code>,
                'API Gateway ID, used to build the ESAM endpoint URL',
                'channel manager, preferences',
              ],
              [
                <code className="text-sm">REGION / STAGE / API_STAGE</code>,
                'Deployment region and API stage, used to build URLs',
                'channel manager, auth config, preferences',
              ],
              [
                <code className="text-sm">ESAM_LOG_GROUP</code>,
                'CloudWatch log group of the signal processor',
                'logs query, preferences',
              ],
              [
                <code className="text-sm">LOG_GROUPS_CONFIG</code>,
                'JSON list of queryable log groups shown in the Logs UI',
                'logs query',
              ],
              [
                <code className="text-sm">USER_POOL_ID</code>,
                'Cognito user pool for auth config and user management',
                'auth config, user management',
              ],
              [
                <code className="text-sm">USER_POOL_CLIENT_ID</code>,
                'Cognito app client served to the frontend at /auth/config',
                'auth config',
              ],
              [
                <code className="text-sm">LOG_LEVEL</code>,
                'Logging level (DEBUG, INFO, WARNING, ERROR); default INFO',
                'all functions',
              ],
            ]}
          />
        </section>
      </div>
    </div>
  );
};

export const DynamoDBConfig: React.FC = () => {
  return (
    <div className="bg-white rounded-xl border border-slate-200 shadow-sm">
      <div className="p-8 border-b border-slate-200">
        <h1 className="text-3xl font-bold text-slate-900 mb-3 flex items-center gap-3">
          <Database className="w-8 h-8 text-indigo-600" />
          DynamoDB Configuration
        </h1>
        <p className="text-lg text-slate-600">
          DynamoDB table structure and configuration
        </p>
      </div>

      <div className="p-8 space-y-8">
        <section>
          <h2 className="text-2xl font-bold text-slate-900 mb-4">Channels Table</h2>
          <div className="space-y-4">
            <div className="p-4 bg-slate-50 rounded-lg border border-slate-200">
              <div className="grid md:grid-cols-2 gap-4 text-sm">
                <div>
                  <div className="text-slate-600 mb-1">Table Name</div>
                  <code className="text-slate-900 font-semibold">{'<stack-name>'}-data</code>
                </div>
                <div>
                  <div className="text-slate-600 mb-1">Partition Key</div>
                  <code className="text-slate-900 font-semibold">channel_id (String)</code>
                </div>
                <div>
                  <div className="text-slate-600 mb-1">Billing Mode</div>
                  <span className="text-slate-900 font-semibold">PAY_PER_REQUEST</span>
                </div>
                <div>
                  <div className="text-slate-600 mb-1">Point-in-Time Recovery</div>
                  <span className="text-green-700 font-semibold">Enabled</span>
                </div>
              </div>
            </div>

            <div>
              <h3 className="text-lg font-semibold text-slate-900 mb-3">Attributes</h3>
              <Table
                headers={['Attribute', 'Type', 'Description']}
                rows={[
                  ['channel_id', 'String', 'Unique channel ID (UUID)'],
                  ['name', 'String', 'Channel name'],
                  ['enabled', 'Boolean', 'Channel status'],
                  ['rules', 'List', 'Array of transformation rules'],
                  ['descriptor_priority', 'String', 'Descriptor priority (optional)'],
                  ['stateful_mode', 'Boolean', 'Stateful mode enabled'],
                  ['created_at', 'String', 'Creation timestamp (ISO 8601)'],
                  ['updated_at', 'String', 'Update timestamp (ISO 8601)']
                ]}
              />
            </div>
          </div>
        </section>

        <section className="bg-gradient-to-br from-indigo-50 to-purple-50 rounded-xl p-6 border border-indigo-100">
          <h3 className="text-lg font-semibold text-slate-900 mb-4">Performance Recommendations</h3>
          <ul className="space-y-2 text-sm text-slate-700">
            <li className="flex items-start gap-2">
              <span className="text-indigo-600 mt-1">•</span>
              <span>Use PAY_PER_REQUEST for unpredictable workloads</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-indigo-600 mt-1">•</span>
              <span>Enable Point-in-Time Recovery for data protection</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-indigo-600 mt-1">•</span>
              <span>Configure TTL on state table for automatic cleanup</span>
            </li>
          </ul>
        </section>
      </div>
    </div>
  );
};

export const CloudWatchConfig: React.FC = () => {
  return (
    <div className="bg-white rounded-xl border border-slate-200 shadow-sm">
      <div className="p-8 border-b border-slate-200">
        <h1 className="text-3xl font-bold text-slate-900 mb-3 flex items-center gap-3">
          <Activity className="w-8 h-8 text-indigo-600" />
          CloudWatch Configuration
        </h1>
        <p className="text-lg text-slate-600">
          Logs, metrics and alarms for monitoring
        </p>
      </div>

      <div className="p-8 space-y-8">
        <section>
          <h2 className="text-2xl font-bold text-slate-900 mb-4">Log Groups</h2>
          <Table
            headers={['Log Group', 'Retention', 'Description']}
            rows={[
              [
                <code className="text-sm">{'/aws/lambda/<stack-name>-signal-processor'}</code>,
                '7 days',
                'ESAM processing logs'
              ],
              [
                <code className="text-sm">{'/aws/lambda/<stack-name>-channel-manager'}</code>,
                '7 days',
                'Channel management logs'
              ],
              [
                <code className="text-sm">{'/aws/lambda/<stack-name>-logs-query'}</code>,
                '7 days',
                'Logs query service logs'
              ]
            ]}
          />
        </section>

        <Callout type="info" title="Custom Dashboard">
          We recommend creating a custom CloudWatch dashboard with the most relevant metrics for your use case.
        </Callout>
      </div>
    </div>
  );
};
